DiskJocker/urls.py
from Store import views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('store/', include('Store.urls', namespace='Store')),
    path('boss/', admin.site.urls),
    path('', views.index, name="index")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      # ...
                      path('__debug__/', include('debug_toolbar.urls')),
                  ] + urlpatterns

Store/urls.py
from django.urls import path, re_path
from . import views
app_name = "Store"
urlpatterns = [
    path('', views.index, name="hello"),
    path('listing', views.listing, name="listing"),
    re_path(r'^search/$', views.search, name="search"),
    path('disque/', views.details, name="detail")
]

Store/models.py
from django.db import models


class Artiste(models.Model):
    nom = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nom


class Contact(models.Model):
    nom = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)


class Message(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # un contact peut laisser un message sur la plateforme
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, null=True)


class Genre(models.Model):
    nom = models.CharField(max_length=255)

    def __str__(self):
        return self.nom


class Type(models.Model):
    nom = models.CharField(max_length=255)

    def __str__(self):
        return self.nom


class Disque(models.Model):
    titre = models.CharField(max_length=255)
    reference = models.IntegerField(blank=True, null=True)
    quantite = models.IntegerField(default=1)
    available = models.BooleanField(default=True)
    photo = models.ImageField(upload_to='file/images/disque')
    appreciation = models.IntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)
    parition = models.DateField(null=True, blank=True)
    continent = models.CharField(max_length = 255, blank=True, null = True)
    pays = models.CharField(max_length = 255, blank=True, null = True)
    # relation entre un disque et les artistes
    artistes = models.ManyToManyField(Artiste, related_name='disques', blank=True)
    played = models.IntegerField(default=0)
    # relation entre un disque et un genre musical
    genre = models.ManyToManyField(Genre,related_name = "genres", blank = True)
    # relation entre un disque et un type (album, mixtape, compilation, EP, etc.
    type = models.ForeignKey(Type, on_delete=models.CASCADE, null=True)
    

    def __str__(self):
        return self.titre


class Chanson(models.Model):
    titre = models.CharField(max_length=255)
    path = models.FileField(upload_to='file/audios/chanson')
    # une chanson est chanté par un ou plusieurs artiste(s)
    artistes = models.ManyToManyField(Artiste, related_name='chansons', blank=True)
    # une chanson est necessairement présent sur un disque
    disque = models.ForeignKey(Disque, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.titre
    


class Booking(models.Model):
    contacted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    disque = models.ForeignKey(Disque, on_delete=models.CASCADE, null=True)
    quantite = models.IntegerField(default=1)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, null=True)


class DiskJocker(models.Model):
    nom = models.CharField(max_length=255)
    logo = models.ImageField(blank=True, null=True, upload_to="file/images/diskjocker")
    banniere_Img = models.ImageField(blank=True, null=True, upload_to="file/images/diskjocker")
    banniere_Vid = models.FileField(blank=True, null=True, upload_to="file/videos/diskjocker")
    def __str__(self):
        return self.nom
    
class Banniere(models.Model):
    nom = models.CharField(max_length = 255)
    image = models.ImageField(upload_to="file/frontend/images/diskjocker")
    def __str__(self):
        return self.nom
    

Store/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Rechercher',
                'required': True
            }
        )
    )

Store/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .forms import SearchForm
from .models import Banniere, Disque, Artiste
from django.core.paginator import Paginator


def index(request):
    # Récupération des cinq banières de la page 
    banieres = Banniere.objects.filter(nom__icontains = 'acceuil')[:5]
    # Récupération des disques valides
    disques = Disque.objects.filter(available=True)
    # Récupération des 12 nouvautés
    disques_new = disques.order_by('-parition')[:12]
    # Récupération des 12 tendances
    disques_trend = disques.order_by('-played')[:12]
    # Récupération des 12 favoris des utilisateurs
    disques_favorite = disques.order_by('-appreciation')[:12]
    banner_newsletter = Banniere.objects.get(nom = "banière newsletter")
    super_mixeur = Banniere.objects.get(nom = "banière super mixeur")
    
    context = {
        'banieres' : banieres,
        'disques_new' : disques_new,
        'disques_trend' : disques_trend,
        'disques_favorite' : disques_favorite,
        'banner_newsletter' : banner_newsletter,
        'super_mixeur' : super_mixeur,
    }
    return render(request, 'Store/index.html', context)


# def listing(request):
#     disques = Disque.objects.all()
#     formSearch = SearchForm()
#     context = {
#         "disques": disques,
#         'form': formSearch,
#     }
#     return render(request, 'Store/listing.html', context)

def listing(request):
    disques = Disque.objects.all().order_by("-id")
    paginator = Paginator(disques, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context ={
        "page_obj" : page_obj,
        "disques" : paginator
    }
    
    return render(request, 'Store/listing.html', context)


def search(request):
    query = request.GET.get('query')
    if not query:
        disques = Disque.objects.all()
    else:
        disques = Disque.objects.filter(titre__icontains=query)
        if not disques.exists():
            disques = Disque.objects.filter(artistes__nom__icontains=query)
            if not disques.exists():
                disques = Disque.objects.filter(chanson__titre__icontains=query)
                if not disques.exists():
                    disques = Disque.objects.filter(genre__nom__iexact=query)
                    if not disques.exists():
                        disques = Disque.objects.filter(type__nom__iexact=query)
                        if not disques.exists():
                            disques = Disque.objects.filter(reference=query)
                            if not disques.exists():
                                disques = Disque.objects.filter(chanson__artistes__nom__icontains=query)
    if len(disques) == 0:
        disques_format = "Nous n'avons trouvé aucun disque!"
    elif len(disques) != 0:
        disques = ['<li>{}</li>'.format(disque.titre) for disque in disques]
        disques_format = "".join(disques)
        disques_format = "<ul>{}</ul>".format(disques_format)

    return HttpResponse(disques_format)


# def details(request, disque_id):
#     disque = Disque.objects.get(pk=disque_id)

#     context = {'disque': disque,}
#     return render(request, 'Store/details.html', context)

def details(request):
    bonjour = "Bonjour les gars !"
    context = {
        'bonjour' : bonjour,
    }
    return render(request, 'Store/details.html', context)

Store/templates/Store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Store/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'Store/css/r_reset.css' %}">
    <link rel="stylesheet" href="{% static 'Store/css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'Store/css/aos.css' %}">
    <title>Document</title>
</head>
<body>
    <header>
        <nav class="d-flex align-items-center">
            <div class="nav-brand logo-index mx-auto" style="background-image: url('{% static 'Store/assets/dj_logo.png' %}');"></div>
            <div class="px-5 py-2 r-contact-us align-items-center justify-content-center">
                <span>
                    <a class="text-white text-decoration-none" href="#">Contactez-nous</a>
                </span>
            </div>
        </nav>
    </header>
    <hr class="r-hr"></hr>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0 w-100">
                    <li class="nav-item">
                        <a class="nav-link active fw-bolder fs-6" aria-current="page" href="{% url 'Store:hello' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fw-bolder fs-6" href="{% url 'Store:listing' %}">Store</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fw-bolder fs-6" href="#">Mode</a>
                    </li>
                </ul>
            </div>
            <form class="d-flex">
                <input class="form-control r-nav-form-control" type="search" placeholder="Rechercher" aria-label="Rechercher">
            </form>
        </div>
    </nav>
      
    {% block 'content' %}
        
    {% endblock  %}
   {% include 'Store/footer.html' %}

    <script src="{% static 'Store/js/aos.js' %}"></script>
    <script>
        AOS.init()
    </script>
    <script src="{% static 'Store/js/bootstrap.bundle.min.js' %}"></script>
    
    <script src="{% static 'Store/js/r_myscript.js' %}"></script>
</body>
</html>

Store/templates/Store/base_pages.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Store/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'Store/css/r_reset.css' %}">
    <link rel="stylesheet" href="{% static 'Store/css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'Store/css/aos.css' %}">
    <title>Document</title>
</head>
<body>

    {% comment %} <section id="base_pages">
        <header class="px-4">
            <nav class="row py-3">
                <div class="col-md-2 logo-container">
                    <div class="logo w-100" style="background-image: url('{% static 'Store/assets/dj_logo.png' %}');">
                        
                    </div>
                </div>
                <div class="col-md-7 row align-items-end">
                    <div class="col-md-4">Home</div>
                    <div class="col-md-4">Store</div>
                    <div class="col-md-4">Mode</div>
                </div>
                <div class="col-md-3">
                    <span><i class="bi bi-search"></i></span>
                </div>
            </nav>
        </header>
    </section> {% endcomment %}
    <header id="base_pages">
        <div class="d-flex container align-items-center">
            <div class="logo-container me-auto">
                <div class="logo-pages w-100 h-100" style="background-image: url('{% static 'Store/assets/dj_logo.png' %}');"></div>
            </div>
            <nav class="navbar order-last order-lg-0 pe-5" id="navbar">
                <ul class="d-flex align-items-center pe-5">
                    <li><a href="{% url 'Store:hello' %}" class="text-decoration-none text-dark fw-semibolder">Acceuil</a></li>
                    <li><a href="{% url 'Store:listing' %}" class="active text-decoration-none text-dark fw-semibolder">Store</a></li>
                    <li><a href="#" class="text-decoration-none text-dark fw-semibolder">Mode</a></li>
                </ul>
            </nav>
            <div class="search-link">
                <span class="r-text-disk-trend fs-2 fw-semibolder">
                    <i class="bi bi-search"></i>
                </span>
            </div>
        </div>
    </header>
    {% block content %}

    {% endblock  %}
    {% include 'Store/footer.html' %}
    <script src="{% static 'Store/js/aos.js' %}"></script>
    <script>
        AOS.init()
    </script>
    <script src="{% static 'Store/js/bootstrap.bundle.min.js' %}"></script>
    
    <script src="{% static 'Store/js/listing.js' %}"></script>
</body>
</html>

Store/templates/Store/catalogue.html
<div class="container-fluid">
    <div class="row">
        {% for disque in disques %}
            <div class="col-md-4 col-sm-6 col-lg-3">
                <img src="{{disque.photo.url}}" class="img-fluid rounded">
                <div class="row tms-3 container">
                    <div class="col-md-2 text-center">
                        <i class="bi bi-heart fs-6"></i>
                    </div>
                    <div class="col-md-8 text-center">
                        {{disque.titre}}
                    </div>
                    <div class="col-md-2 text-center">
                        <span class="badge mon-badge">
                            {{disque.genre}}
                        </span>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:4 %}<div class="clearfix py-2"></div>{% endif %}
        {% empty %}
           <div class="col-md-12 text-center">
                Aucun album n'est disponoble ou n'été trouvé...
           </div>
        {% endfor %}
    </div>
</div>

Store/templates/Store/details.html
<h2>{{bonjour}}</h2>

Store/templates/Store/footer.html
{% load static %}
<footer class="container py-4">
    <div class="row">
         <div class="col-md-5 d-flex justify-content-start align-items-end">
            <div class="row">
                <div class="col-md-1 gx-5">
                    <span class="r-text-disk-trend fw-semibolder fs-5">
                        <i class="bi bi-google"></i>
                    </span>
                </div>
                <div class="col-md-1 gx-5">
                    <span class="r-text-disk-trend fw-semibolder fs-5">
                        <i class="bi bi-whatsapp"></i>
                    </span>
                </div>
                <div class="col-md-1 gx-5">
                    <span class="r-text-disk-trend fw-semibolder fs-5">
                        <i class="bi bi-facebook"></i>
                    </span>
                </div>
            </div>
         </div>
         <div class="col-md-2">
            {% comment %} <img src="{% static 'Store/assets/dj_logo.png' %}" class="img-fluid"> {% endcomment %}
            <div class="w-100 logo-footer" style="background-image: url('{% static 'Store/assets/dj_logo.png' %}');"></div>
         </div>
         <div class="col-md-5 d-flex justify-content-end align-items-end">
            <span class="r-text-disk-trend">&copy; Copyright 2023</span>
         </div>
    </div>
</footer>

Store/templates/Store/index.html
{% extends 'Store/base.html' %}
{% load static %}

{% block 'content' %}
    <section id="hero" class="container">
        <div id="carouselExampleCaptions" class="carousel slide w-100 h-100" data-bs-ride="false">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
            </div>
            <div class="carousel-inner h-100 w-100">
                {% for banner in banieres %}
                    {% if forloop.first %}
                        <div class="carousel-item active h-100 w-100">
                            <div class="r-banner-index w-100 h-100 rounded" style="background-image:linear-gradient(to right bottom,#6035355e, #60353570),url({{banner.image.url}});"></div>
                        </div>
                    {% else %}
                        <div class="carousel-item h-100 w-100">
                            <div class="r-banner-index w-100 h-100 rounded" style="background-image:linear-gradient(to right bottom,#6035355e, #60353570),url({{banner.image.url}});"></div>
                        </div>
                    {% endif %}    
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
        </div>
    </section>
    <section>
        <div class="kind py-5 d-flex align-items-center justify-content-center">
            <div class="row">
                <div class="col-md-4 gx-4 r-btn-new">
                    <button class="btn r-btn text-white index-kind-btn" id="index_new">Nouveaux</button>
                </div>
                <div class="col-md-4 gx-4 r-btn-trend">
                    <button class="btn r-btn text-white index-kind-btn" id="index_trend">Tendances</button>
                </div>
                <div class="col-md-4 gx-4 r-btn-favorite">
                    <button class="btn r-btn text-white index-kind-btn" id="index_favorite">Favoris</button>
                </div>
            </div>
        </div>
    </section>
    <section class="section-new-disk index-kind-section" id="section_index_new">
        <div class="py-4 w-100 d-flex align-items-center justify-content-center">
            <span class="text-dark fw-bolder">Nouveautés</span>
        </div>
        {% include 'Store/list.html' with disques=disques_new %}
    </section>
    <section class="section-trend-disk index-kind-section d-none" id="section_index_trend">
        <div class="py-4 w-100 d-flex align-items-center justify-content-center">
            <span class="text-dark fw-bolder">Tendances</span>
        </div>
        {% include 'Store/list.html' with disques=disques_trend %}
    </section>
    <section class="section-favorite-disk index-kind-section d-none" id="section_index_favorite">
        <div class="py-4 w-100 d-flex align-items-center justify-content-center">
            <span class="text-dark fw-bolder">Favoris</span>
        </div>
        {% include 'Store/list.html' with disques=disques_favorite %}
    </section>

    <section class="py-4 mt-5 mb-2" id="joinus"  style="background-image:linear-gradient(to right bottom,#6035355e, #60353570),url({{banner_newsletter.image.url}});">
        <div class="w-100 py-4 d-flex align-items-center justify-content-center">
           <span class="text-white fw-bolder fs-3">Abonnez-vous à notre newsletter</span>
        </div>
        <div class="w-100 py-4 d-flex align-items-center justify-content-center">
            <div class="text-white text-start fs-4">
                Abonnez-vous à notre newsletter pour ne rien rater de nos <br>produits et nos activités.
            </div>
        </div>
        <div class="container w-100">
            <div class="w-100 py-4 d-flex align-items-center justify-content-end">
                <form class="r-form-group py-3">
                    <div class="r-before-email-form align-items-center d-flex px-4">
                        <div><span class="fs-semibolder fs-5 text-white">Abonnez-vous à la newsletter</span> <span class="fs-5 fw-semibolder text-white"><i class="bi bi-arrow-right-circle-fill"></i></span></div>
                    </div>
                    <div class="r-form-div d-flex align-items-center justify-content-end d-none">
                        <div class="r-gmail-btn">
                            <span class="fs-3 fw-bolder text-white"><i class="bi bi-google"></i></span>
                        </div>
                        <input class="r-form-email fs-6 pe-2 py-3 fw-semibolder" type="email" placeholder="Votre email...">
                    </div>
                </form>
            </div>
        </div>
    </section>

    <section class="py-4 w-100 d-flex align-items-center justify-content-center" >
        <span class="mt-5 mb-3 r-text-disk-trend fw-bolder">Decouvrez le super mixeur</span>
    </section>
    <section id="super_mixeur" style="background-image:linear-gradient(to right bottom,#6035355e, #60353570),url({{super_mixeur.image.url}});" class="py-4">
        <div class="py-4 container w-100 d-flex align-items-center justify-content-end">
            <div class="pt-4 r-text-disk-trend fw-bolder">
                Avec le super mixeur rejoingnez le paradis musical avec vos morçeaux préférés, faites vibez vos amis et invités aux divers fêtes.Et surtout faites un malheur aux tampans de vos voisins tous les weekends.
            </div>
        </div>
        <div class="w-100 d-flex justify-content-end align-items-center container py-4">
            <div class="message-box text-white fw-bolder py-2 px-1 mb-4">Tester le super mixeur</div>
        </div>
        
    </section>
    <section>
        <div class="w-100 py-5 part-services">
            <div class="bg-white div-services">
                <div class="d-flex align-items-center justify-content-center py-3">
                    <span class="r-text-disk-trend fw-bolder">Nos services</span>
                </div>
                <div class="r-services pt-1 pb-5">
                    <div class="r-service bg-primary">

                    </div>
                    <div class="r-service bg-primary"></div>
                    <div class="r-service bg-primary"></div>
                </div>
            </div>
        </div>
    </section>
    
{% endblock  %}

Store/templates/Store/list.html
{% load static %}

<div class="container">
  {% for disque in disques %}
      {% if forloop.first %}
          <div class="row">
      {% endif %}
      {% if forloop.counter|divisibleby:"3" %}
              <div class="col-md-4">
                  <div class="row">
                      <div class="disk-place">
                          <div class="disk-img w-100">
                              <img class="img-fluid rounded w-100 h-100" src="{{disque.photo.url}}">
                              <div class="r-play-btn">
                                  <a href="{% url 'Store:detail' %}" target="_blank" class="r-play-link">
                                    <div class="r-triangle"></div>
                                  </a>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-10 r-text-disk-new text-end">
                          {{disque.titre}}
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-10">
                          {% for artiste in disque.artistes.all %}
                              {% if forloop.counter|divisibleby:"2" %}
                                  {% if forloop.last %}
                                      <span class="r-text-disk-new"> & {{artiste.nom}}</span>
                                  {% else %}
                                      <span class="r-text-disk-new"> & {{artiste.nom}} & </span>  
                                  {% endif %}
                              {% else %}
                                  <span class="r-text-disk-new">{{artiste.nom}}</span>
                              {% endif %}
                          {% endfor %}
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-2 d-flex align-items-center justify-content-center">
                          <span><i class="bi bi-heart"></i></span>
                      </div>
                      <div class="col-md-10">
                          <span class="r-text-disk-new">{{disque.appreciation}}</span>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-10 d-flex justify-content-end">
                          <div class="played-badge-circle">
                              <div class="r-disk-played-circle-demo d-none"></div>
                              <div class="r-disk-played-icon d-flex align-items-center justify-content-center d-none">
                                  <span class="text-light"><i class="bi bi-music-note-beamed"></i></span>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="row">
      {% else %}
              <div class="col-md-4">
                  <div class="row">
                      <div class="disk-place">
                          <div class="disk-img w-100">
                              <img class="img-fluid rounded w-100 h-100" src="{{disque.photo.url}}">
                              <div class="r-play-btn">
                                <a href="{% url 'Store:detail' %}" target="_blank" class="r-play-link">
                                    <div class="r-triangle"></div>
                                </a>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-10 r-text-disk-new text-end">
                          {{disque.titre}}
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-10">
                          {% for artiste in disque.artistes.all %}
                              {% if forloop.counter|divisibleby:"2" %}
                                  {% if forloop.last %}
                                      <span class="r-text-disk-new"> & {{artiste.nom}}</span>
                                  {% else %}
                                      <span class="r-text-disk-new"> & {{artiste.nom}} & </span>  
                                  {% endif %}
                              {% else %}
                                  <span class="r-text-disk-new">{{artiste.nom}}</span>
                              {% endif %}
                          {% endfor %}
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-2 d-flex align-items-center justify-content-center">
                          <span><i class="bi bi-heart"></i></span>
                      </div>
                      <div class="col-md-10">
                          <span class="r-text-disk-new">{{disque.appreciation}}</span>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-10 d-flex justify-content-end">
                          <div class="played-badge-circle">
                              <div class="r-disk-played-circle-demo d-none"></div>
                              <div class="r-disk-played-icon d-flex align-items-center justify-content-center d-none">
                                  <span class="text-light"><i class="bi bi-music-note-beamed"></i></span>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
      {% endif %}
      {% if forloop.last %}
              </div>
      {% endif %}
  {% empty %}
      <div class="row">
          <div class="ol-md-12 text-center">
              <span class="r-text-disk-new">
                  Aucun album n'est disponible
              </span>
          </div>
      </div>
  {% endfor %}
<div>

Store/templates/Store/searchForm.html
<div class="row">
  <div class="col-lg-12 py-4">
      <form method="get" action="{% url 'Store:search' %}">
        {{form.query}}
      </form>
  </div>
</div>